version: 2.1
orbs:
  node: circleci/node@1.1.6
  windows: circleci/windows@2.2.0
jobs:
  test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: "Install dependencies"
                command: cd WhaleSpotting/react-app; npm install
            - run:
                name: "Run tests"
                command: cd WhaleSpotting/react-app; npm test
            - run:
                name: "Run lint"
                command: cd WhaleSpotting/react-app; npm run lint
  test-backend:
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "WhaleSpotting/WhaleSpotting.csproj" }}
      - run:
          name: "Restore project"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "WhaleSpotting/WhaleSpotting.csproj" }}
      - run:
          name: "Run tests"
          command: dotnet.exe test
workflows:
  test:
    jobs:
      - test-frontend
      - test-backend
